#!/usr/bin/env bash
# gen-research-map.sh — regenerate the always-current structural research map for teri.
#
# AUTO-RUN at session start (.claude/settings.json + .codex/hooks.json SessionStart) and
# safe to run by hand. Writes code-research/references/research-ledger.md (gitignored,
# ephemeral, always reflects current source). Prints a one-line summary to stdout so the
# session-start hook can surface a reference into the agent's context.
#
# Durable analysis (parity verdict, architecture) lives in RUNBOOK.md §12 + CLAUDE.md;
# this file is the navigation aid, not the source of truth. Fast (<2s), no hard deps.
#
# Flags:
#   --reindex   also (re)build the git-kb code index before pulling symbol/hotspot stats
set -euo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || printf '%s' "$PWD")"
cd "$root"
out="code-research/references/research-ledger.md"
mkdir -p "$(dirname "$out")"

reindex=0
[ "${1:-}" = "--reindex" ] && reindex=1

# --- cheap, always-available facts -------------------------------------------------
stamp="$(date -u '+%Y-%m-%d %H:%M UTC')"
sha="$(git rev-parse --short HEAD 2>/dev/null || echo '?')"
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"

rs_files="$(git ls-files 'src/*.rs' 'src/**/*.rs' 2>/dev/null | wc -l | tr -d ' ')"
rs_loc="$(git ls-files 'src/*.rs' 'src/**/*.rs' 2>/dev/null | xargs cat 2>/dev/null | wc -l | tr -d ' ')"
test_fns="$(grep -rhoE '#\[(tokio::)?test\]' src tests 2>/dev/null | wc -l | tr -d ' ')"
test_files="$(git ls-files 'tests/*.rs' 2>/dev/null | wc -l | tr -d ' ')"
routes="$(grep -rhoE '\.route\(' src/api 2>/dev/null | wc -l | tr -d ' ')"

# CLI subcommands — clap derive variants used as `Commands::<Variant>` in main.rs, lowercased
subcmds="$(grep -oE 'Commands::[A-Z][A-Za-z]+' src/main.rs 2>/dev/null \
  | sed 's/Commands:://' | sort -u | tr 'A-Z' 'a-z' | tr '\n' ' ' || true)"
[ -z "$(printf '%s' "$subcmds" | tr -d '[:space:]')" ] && subcmds="run serve"

modules="$( (ls -d src/*/ 2>/dev/null | sed 's#src/##; s#/##'; ls src/*.rs 2>/dev/null | sed 's#src/##; s#\.rs$##') \
  | sort -u | grep -v '^main$' | tr '\n' ' ' )"

# --- opportunistic git-kb code intelligence ----------------------------------------
kb_line="not indexed — run \`scripts/gen-research-map.sh --reindex\` (or \`git-kb code index src\`)"
if command -v git-kb >/dev/null 2>&1; then
  if [ "$reindex" = "1" ]; then git-kb code index src >/dev/null 2>&1 || true; fi
  doctor="$(git-kb code doctor --json 2>/dev/null || echo '{}')"
  syms="$(printf '%s' "$doctor" | grep -oE '"symbol_count"[: ]+[0-9]+' | grep -oE '[0-9]+' || echo 0)"
  files="$(printf '%s' "$doctor" | grep -oE '"file_count"[: ]+[0-9]+' | grep -oE '[0-9]+' || echo 0)"
  edges="$(printf '%s' "$doctor" | grep -oE '"call_edge_count"[: ]+[0-9]+' | grep -oE '[0-9]+' || echo 0)"
  if [ "${syms:-0}" -gt 0 ]; then
    kb_line="${syms} symbols, ${files} files, ${edges} call edges (git-kb code index)"
  fi
fi

# --- write the living map ----------------------------------------------------------
cat > "$out" <<EOF
# Research Map — teri (AUTO-GENERATED)

> Regenerated by \`scripts/gen-research-map.sh\` at every session start; **gitignored, do not
> hand-edit** — edits are overwritten. This is the always-current *navigation map*. The durable
> analysis (MiroFish parity verdict, capability matrix) is authoritative in **RUNBOOK.md §12**;
> architecture + guards are in **CLAUDE.md**.

**Generated:** ${stamp} · **Commit:** ${sha} (${branch})
**Source:** ${rs_files} Rust files in \`src/\`, ${rs_loc} LOC · **Tests:** ${test_fns} test fns across ${test_files} \`tests/\` suites · **HTTP routes:** ${routes}

## Entry points
- \`src/main.rs\` — clap CLI; subcommands: ${subcmds:-run serve}. Arg-parse-before-config (\`--help\`/\`--version\` keyless); both gate on \`preflight_backend\`.
- \`src/main.rs::run_cmd\` → \`teri::pipeline::run_pipeline\` — the in-process 5-stage composition (seed → graph → persona → sim → report).
- \`src/server.rs::create_app\` / \`serve\` — axum HTTP server (\`/health\` + \`/api/*\`).
- \`src/lib.rs\` — library surface (modules re-exported).

## Module inventory (\`src/\`)
${modules}

## External interface surface
- \`/api/graph/*\` (\`src/api/graph.rs\`), \`/api/simulation/*\` (\`src/api/simulation.rs\`), \`/api/report/*\` (\`src/api/report.rs\`) — ${routes} routes total, plus SSE streams.
- CLI: \`teri run\` (one-shot pipeline), \`teri serve\` (REST server).

## Code intelligence
- ${kb_line}

## Claims to verify (regenerate-stable scaffold — confirm against current source, never docs)
- [ ] \`teri run\` is wired to \`pipeline::run_pipeline\` (NOT a "Pipeline not yet implemented" stub) — \`src/main.rs\`.
- [ ] All five pipeline stages call real services (no canned simulation) — \`src/pipeline.rs\`.
- [ ] Backend honesty guard fail-closed (refuses unreachable/empty-model/stub) — \`src/preflight.rs::verify_backend\`.
- [ ] Provider selection live (OpenAI/Anthropic/Gemini via \`ProviderAdapter\`) — \`src/api/mod.rs::build_provider_llm\`.
- [ ] Full \`cargo test\` suite green — run \`cargo test\`.

## Where the deep analysis lives (read these, not this generated file)
- **RUNBOOK.md §12** — MiroFish parity & capability matrix (authoritative verdict).
- **CLAUDE.md** — architecture, guards, secrets contract, build/test/verify.
- ICM / session memory — cross-session continuity.
EOF

# one-line summary for the session-start hook to inject into agent context
printf 'teri research map refreshed: %s (%s LOC, %s test fns, %s routes) → %s\n' \
  "$sha" "$rs_loc" "$test_fns" "$routes" "$out"
